version: '3.9'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"
    
services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - TZ="America/New_York"
      - PUID=${PUID}
      - PGID=${PGID}
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
      - SWARMPIT_DOCKER_API=1.48
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 888:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
      - backend
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.http.routers.${ROUTER_NAME}.rule=Host(`${ROUTER_NAME}.${ROOT_DOMAIN}`)
        - traefik.http.routers.${ROUTER_NAME}.middlewares=chain-no-auth@file
        - traefik.http.routers.${ROUTER_NAME}.service=${ROUTER_NAME}-svc
        - traefik.http.services.${ROUTER_NAME}-svc.loadbalancer.server.port=8080
    logging: *default-logging

  db:
    image: couchdb:2.3.1
    # environment:
      # - COUCHDB_USER=admin
      # - COUCHDB_PASSWORD=admin123
    volumes:
      - /mnt/glusterfs/swarmpit/db-data:/opt/couchdb/data
    networks:
      - backend
    environment:
      - TZ="America/New_York"
    deploy:
      placement:
        constraints: 
          - node.labels.WIRED == YES
          - node.labels.GLUSTER == YES
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M
    logging: *default-logging

  influxdb:
    image: influxdb:1.8.10
    volumes:
      - /mnt/glusterfs/swarmpit/influx-data:/var/lib/influxdb
    networks:
      - backend
    environment:
      - TZ="America/New_York"
    deploy:
      placement:
        constraints: 
          - node.labels.WIRED == YES
          - node.labels.GLUSTER == YES
      resources:
        limits:
          cpus: '0.60'
          memory: 512M
        reservations:
          cpus: '0.30'
          memory: 128M
    logging: *default-logging

  agent:
    image: swarmpit/agent:latest
    environment:
      - TZ="America/New_York"
      - DOCKER_API_VERSION=1.48
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M
    logging: *default-logging


networks:
  backend:
    name: ${BACKEND_NETWORK_NAME}
    external: true
  traefik-public:
    external: true


