version: '3.9'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"
    

services:
  homebridge:
    image: jackietreehorn/${STACK_NAME}:latest  # homebridge/homebridge:latest
    # hostname: "{{.Node.Hostname}}"
    networks:
      - host
    environment:
      - TZ="America/New_York"
      - PUID=${PUID}
      - PGID=${PGID}
      - HOMEBRIDGE_CONFIG_UI_PORT = 8581
      - HOMEBRIDGE_CONFIG_UI = 1
      - ENABLE_AVAHI=0
    volumes:
      - /mnt/glusterfs/homebridge:/homebridge
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.GLUSTER == YES
      labels:   # Using Traefik rule file since this container runs in host network mode - see traefik stack rules
        # - traefik.enable=true
        # - traefik.swarm.network=traefik-public
        # - traefik.http.routers.${ROUTER_NAME}.rule=Host(`${ROUTER_NAME}.${ROOT_DOMAIN}`)
        # - traefik.http.routers.${ROUTER_NAME}.middlewares=chain-no-auth@file
        # - traefik.http.routers.${ROUTER_NAME}.service=${ROUTER_NAME}-svc
        # - traefik.http.services.${ROUTER_NAME}-svc.loadbalancer.server.port=8581
    logging: *default-logging


networks:
  host:
    external: true
    name: host