version: "3.9"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  gantry:
    image: jackietreehorn/${STACK_NAME}:latest # shizunge/gantry:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    environment:
      - "TZ=America/New_York"
      - GANTRY_NODE_NAME={{.Node.Hostname}}
      # The gantry service is able to find the name of itself service. Use GANTRY_SERVICES_SELF when you want to set a different value.
      # - "GANTRY_SERVICES_SELF=${STACK}_gantry"
      - GANTRY_SLEEP_SECONDS=0
    deploy:
      replicas: 0
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: none
      labels:
        - swarm.cronjob.enable=true
        # every hour
        - swarm.cronjob.schedule=0 * * * *
        - swarm.cronjob.skip-running=true
    logging: *default-logging

  cronjob:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    environment:
      - "TZ=America/New_York"
    deploy:
      placement:
        constraints:
          - node.role==manager
    logging: *default-logging

networks:
  backend:
    name: ${BACKEND_NETWORK_NAME}
    external: true
