http:
  middlewares:
    middlewares-secure-headers-traefik:
      headers:
        # ===========================
        # CORS (Cross-Origin Support)
        # ===========================
        accessControlAllowOriginListRegex:
          - "^https://([a-z0-9-]+\\.)*yourdomain\\.co$"
          - "^https://yourdomain\\.co$"
        # with wildcard subdomain support and credentials
        # accessControlAllowOriginList: ["*"]
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          - PATCH
        accessControlAllowHeaders:
          - Authorization
          - Content-Type
          - Accept
          # Client-sent headers only
          - X-Requested-With
          # Traefik already takes care of this
          # - X-Forwarded-For
          # - X-Forwarded-Proto
          # - X-Forwarded-Host
          # - X-Forwarded-Port
        accessControlAllowCredentials: true
        accessControlMaxAge: 3600

        # =================================
        # WebSocket Handling (Traefik-Specific)
        # =================================
        # Traefik v3 automatically handles WebSocket upgrades when detected
        # These headers are ONLY added during actual WebSocket upgrades, but left Upgrade and Connection in anyway
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          # Upgrade: "websocket" # traefik takes care
          # Connection: "upgrade" # traefik takes care

        # ====================
        # Security Headers
        # ====================
        stsSeconds: 63072000  # 2 years for preload compliance
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true    # Critical for HSTS enforcement
        frameDeny: true
        contentTypeNosniff: false # <- might cause issue when used on traefik's API dashboard - disable it
        browserXssFilter: true

        # =================================
        # Privacy Headers
        # =================================
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=()"

        # ====================
        # CSP
        # ====================
        contentSecurityPolicy: >
          default-src 'self';
          script-src 'self' 'unsafe-inline' 'unsafe-eval' https: data:;
          style-src 'self' 'unsafe-inline' https:;
          font-src 'self' https: data:;
          img-src 'self' https: data:;
          connect-src 'self' https:;
          frame-ancestors 'none';
          object-src 'none';

        # =================================
        # Response Headers
        # =================================
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          Server: ""
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"

        # ====================
        # Proxy Headers
        # ====================
        hostsProxyHeaders:
          - X-Forwarded-Host