http:
  middlewares:
    middlewares-secure-headers-v3:
      headers:
        # CORS (Cross-Origin Resource Sharing)
        # accessControlAllowOriginListRegex:
        #   - "^https://([a-z0-9-]+\\.)*bitwisesolutions\\.co$" # with wildcard subdomain support and credentials
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
          - PATCH
        accessControlAllowHeaders:
          - Authorization
          - Content-Type
          - X-Requested-With
          - X-Forwarded-For
          - X-Forwarded-Proto
          - X-Forwarded-Host
          - X-Forwarded-Port
        accessControlAllowCredentials: true
        accessControlMaxAge: 3600

        # HTTP Strict Transport Security (HSTS)
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true # can be tricky

        # X-Frame-Options (clickjacking protection)
        frameDeny: true  # Use this OR customFrameOptionsValue

        # MIME Sniffing Protection
        contentTypeNosniff: true

        # XSS Protection
        browserXssFilter: true

        # Referrer Policy
        referrerPolicy: "strict-origin-when-cross-origin" #"strict-origin" 
        # referrerPolicy: "same-origin"

        # Permissions Policy (formerly Feature Policy)
        permissionsPolicy: "camera=(), microphone=(), geolocation=(), payment=(), usb=(), vr=()"

        # Content Security Policy (optional, can be strict)
        # contentSecurityPolicy: "default-src 'self'; img-src *; media-src *; script-src 'self'; style-src 'self';"

        # Custom Response Headers
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          Server: ""  # Hide server info
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "DENY"
          X-XSS-Protection: "1; mode=block"
          Referrer-Policy: "strict-origin-when-cross-origin" #"strict-origin"
          Permissions-Policy: "camera=(), microphone=(), geolocation=(), payment=()"

        # Proxy Headers (optional, usually handled by Traefik)
        hostsProxyHeaders:
          - "X-Forwarded-Host"
